#!/usr/bin/env python
# -*- coding: UTF-8 -*- 

import sys
import tweepy
import json

consumer_key = '9aeAYlgVhJpERslBMoSg'
consumer_secret = 'fYK4C6MRtBMhknkhDlPaxO4LJ5PWZk1bL5M9eSPR4'
access_token = '26397958-ScQmgJgVcJkSJutjUaj9KnwQcekf0eiZfhErEhIvl'
access_token_secret = 'nDX6gpJOc1BxT8cJXurSjHs4g3DN4NVnrJNXCP3f1xzTF'

auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)

api = tweepy.API(auth)


results = api.search(q="monkey OR coconut", rpp=100, lang="en")

for result in results:
	print result.text.encode('utf-8')
